### ISSUE TITLE
可以帮忙提供下这个版本对应的砸壳ipa

### ISSUE THREAD

**Issue by AceDong0803** [Nododo/HookDouYin#1]

**Comment by AceDong0803** [comment]
最新版本的检测弹窗已经不能这么去掉了，非常感谢哈。可以给个联系方式嘛

**Comment by LittleLydia** [comment]
> 最新版本的检测弹窗已经不能这么去掉了，非常感谢哈。可以给个联系方式嘛

最新版本去掉弹框也还是会自动退出，有什么解决办法获解决思路吗？

**Comment by ITyongzhen** [comment]
> 最新版本的检测弹窗已经不能这么去掉了，非常感谢哈。可以给个联系方式嘛

同问

**Comment by Nododo** [comment]
因换工作，电脑更换，旧项目已丢失，大家可以通过其它方式下载历史版本。
